### ISSUE TITLE
Hey x

### ISSUE THREAD

**Issue by oleanderghum** [oleanderghum/xx#2]
How are you holding there? Leave a message here, only here please

**Comment by oleanderghum** [comment]
Here I am still waiting for you

**Comment by shayymaa** [comment]
your last email made me laugh，honestly 
hhhhh 
i knew that was you,even when I saw the first word I definitely knew it was u

**Comment by oleanderghum** [comment]
ahhhhhh finaly

**Comment by oleanderghum** [comment]
How things going?

**Comment by oleanderghum** [comment]
Hey how are you

**Comment by shayymaa** [comment]
I don’t know ur still waiting,and your message made me think a lot,and I’m trying to organize my thoughts and words.
I thought you are waiting for my longer message,which I’ll write to you later

**Comment by shayymaa** [comment]
I didn’t know I can made my peace with it,with my waiting. But as you see. I made it

**Comment by oleanderghum** [comment]
Yeah I'LL  wait and i'M super worry about you

**Comment by shayymaa** [comment]
What could I say? It’s just,well ,everything is fine,don’t worry .

**Comment by oleanderghum** [comment]
Thought you'd be mad at me..

**Comment by shayymaa** [comment]
I even thought when you contact me,maybe it’s time to back to school

**Comment by oleanderghum** [comment]
When I saw your #comment,my heart is beating like 180 bpm

**Comment by oleanderghum** [comment]
Like I'm really talking to you

**Comment by shayymaa** [comment]
I’m not mad at you, I truly found my peace with it.

**Comment by oleanderghum** [comment]
By this, in this, some kind of geek bar

**Comment by oleanderghum** [comment]
You know why I stopped contact?

**Comment by oleanderghum** [comment]
Any ideas what's going on here?

**Comment by shayymaa** [comment]
Actually I’m worried about you and I don’t think what you said in your email is a good explanation,so I’m still waiting for your explanation,face to face. I think that will be the only proper way. I can still wait

**Comment by shayymaa** [comment]
I don’t know anything,even after reading your messages

**Comment by oleanderghum** [comment]
OK, but

**Comment by oleanderghum** [comment]
There are something I need you to do, for me

**Comment by shayymaa** [comment]
I..I’m just . I don’t know what happened,all I know is that everything happened quite suddenly

**Comment by shayymaa** [comment]
Why I made you live in such a tough way ,that’s not my intention

**Comment by oleanderghum** [comment]
Don't answer my phone, or any phone number from the city I lived, you know where I mean.
If you pick up any phone call that sounds weird,or about me,cut it immediately
I know this sounds awkward, but please do as I say, ok?

**Comment by shayymaa** [comment]
you made me nervous

**Comment by shayymaa** [comment]
why you just explain for this

**Comment by oleanderghum** [comment]
Can you do this for me?

**Comment by shayymaa** [comment]
What you want me to do is easy,but you made me nervous,understand?

**Comment by oleanderghum** [comment]
I'm in the middle of tornado,and I don't want you to get hurt

**Comment by shayymaa** [comment]
what we are doing is destined to get hurt,we deserved it. I’m not afraid of that

**Comment by oleanderghum** [comment]
You register this by email address right?  Anyone of us talk to each other will get feedback by email, so we can keep in touch here, but you need to open email app notification first

**Comment by oleanderghum** [comment]
Some hurt has to get and some not, less is better

**Comment by shayymaa** [comment]
but for me，the one not in the know,be kept in the dark, this really scares me

**Comment by shayymaa** [comment]
Okay if it’s difficult to explain here, I wanna u make me a promise

**Comment by oleanderghum** [comment]
Dark room is the safest place, trust me, danger outside. I'm not trying to fool you or what, I'm trying to keep you away from jeopardy

**Comment by oleanderghum** [comment]
# **Promise what?**

**Comment by shayymaa** [comment]
Don’t make yourself live so toughly,or that will take me down.
Don’t hurt yourself ,don’t hurt anybody,that’s not I want 
Btw,Don’t hurt your phone .😂

**Comment by oleanderghum** [comment]
See it

**Comment by oleanderghum** [comment]
I can do that

**Comment by oleanderghum** [comment]
So how about you, your days

**Comment by shayymaa** [comment]
you know what，when I kept my waiting and worried about you l finally realized that all I want was your happiness,anything except this would be the luxury or a gift for me , if you would get hurt because of what I want, I’m done asking for all these. I want you to be happy,i wanna be your source of happiness.

**Comment by shayymaa** [comment]
my days are boring,just staying home day and night,sleeping,working for my assignment ,listening to the music, reading books,watching videos.thats all

**Comment by oleanderghum** [comment]
[https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1598115936,836704453&fm=27&gp=0.jpg](url)

**Comment by oleanderghum** [comment]
You are the source, and days without you like now, I'm not happy.

**Comment by oleanderghum** [comment]
![1280px-uss_stark](https://user-images.githubusercontent.com/36097985/35768527-01badad4-0938-11e8-8d73-13a23f40da5e.jpg)

**Comment by oleanderghum** [comment]
You can attach photos by dragging them to the clipboard, they will transfer to a code but show as a picture,if you want to share

**Comment by shayymaa** [comment]
Since you asked me to wait till today I didn’t go out, finally this afternoon I think maybe I should go out for some fresh air so I went shopping for my mom and ate out with my friend,when I saw your message I decided to talk about you with her,actually not so much,i even know what I was talking about.cuz i wanted a quiet place to read your message , I ended my dinner in a hurry

**Comment by shayymaa** [comment]
im not blaming you or complaining,I’m trying to show you my peace,to comfort you

**Comment by oleanderghum** [comment]
I don't mind to take the blame

**Comment by oleanderghum** [comment]
Oh let me

**Comment by oleanderghum** [comment]
Like what

**Comment by shayymaa** [comment]
how could i bare to？

**Comment by oleanderghum** [comment]
Let me know

**Comment by shayymaa** [comment]
like nothing， ｉcan’t remember anything to blame you this moment

**Comment by shayymaa** [comment]
Don’t be so serious

**Comment by oleanderghum** [comment]
Not serious,but curious

**Comment by shayymaa** [comment]
أحبك

**Comment by oleanderghum** [comment]
🏡

**Comment by shayymaa** [comment]
whats that for

**Comment by oleanderghum** [comment]
You tired?

**Comment by shayymaa** [comment]
not yet

**Comment by oleanderghum** [comment]
Using computer or mobile?

**Comment by shayymaa** [comment]
📱

**Comment by oleanderghum** [comment]
Cool, I stayed up till 7am last night

**Comment by oleanderghum** [comment]
Insomniac hit again

**Comment by oleanderghum** [comment]
I was thinking about you all night long

**Comment by shayymaa** [comment]
try to sleep well tonight，okey？

**Comment by oleanderghum** [comment]
I don't care about sleeping

**Comment by shayymaa** [comment]
ｉwake up times every night,just to check your message😂

**Comment by shayymaa** [comment]
I do,i do care about your sleeping,your mind,your health, your life

**Comment by oleanderghum** [comment]
You don't wake up tonight 🙂

**Comment by oleanderghum** [comment]
What life, it's half life

**Comment by shayymaa** [comment]
Just do all these for me,okay?

**Comment by oleanderghum** [comment]
I mean I was thinking about you, now just miss,but like really think,think about, and really concentrated

**Comment by shayymaa** [comment]
You made me wait,here comes my requirement😏

**Comment by oleanderghum** [comment]
Will do

**Comment by oleanderghum** [comment]
That is sweet

**Comment by shayymaa** [comment]
not to make yourself so hard，I’ll blame myself and I can do nothing to help you

**Comment by oleanderghum** [comment]
Still alive, don't worry,you help if you do what I said which SCARED you,would be a really big favor

**Comment by shayymaa** [comment]
Whom I’m waiting for is not just an alive guy,okay? I’ll do as you asked,and you,you’re supposed to take good care of yourself for me,deal?

**Comment by oleanderghum** [comment]
Deal , I'll stay alive and fresh😀

**Comment by shayymaa** [comment]
and...clean-washed ???🙈

**Comment by oleanderghum** [comment]
Yuuuuuuup

**Comment by shayymaa** [comment]
ohhh 😌kindled me with passion

**Comment by shayymaa** [comment]
Hey

**Comment by shayymaa** [comment]
I’ saying

**Comment by shayymaa** [comment]
GREAT to see you again

**Comment by shayymaa** [comment]
good to talk to you again

**Comment by shayymaa** [comment]
Really really

**Comment by shayymaa** [comment]
Here comes my migraine again.
dream of me and sleep well.
see you soon in your dream

**Comment by oleanderghum** [comment]
Sorry I black out..,,,,

**Comment by shayymaa** [comment]
You sent me a message in Chinese in my dream but.. I can’t remember any words.only remember that’s not what I want to see,bad letters and bad words,actually I tried not to forget it to blame you....ahhhhh I failed,lucky you
