### ISSUE TITLE
Good morning

### ISSUE THREAD

**Issue by oleanderghum** [oleanderghum/xx#3]
**How's you headache? Feeling better?**

**Comment by shayymaa** [comment]
fine，don’t worry,you’ll get used to it 😅

**Comment by oleanderghum** [comment]
sleep well?

**Comment by shayymaa** [comment]
Little tired because of the dream

**Comment by oleanderghum** [comment]
yes?

**Comment by shayymaa** [comment]
You sent me a message in Chinese in my dream but.. I can’t remember any words.only remember that’s not what I want to see,bad letters and bad words,actually I tried not to forget it to blame you....ahhhhh I failed,lucky you

**Comment by shayymaa** [comment]
this kinda dream 😅

**Comment by oleanderghum** [comment]
A red brick 3 floors building

**Comment by shayymaa** [comment]
found me？met me？

**Comment by oleanderghum** [comment]
When I get into that room,found lots of co-workers there, and you are sit in the middle of them, I wonder how to get you out of there

**Comment by shayymaa** [comment]
why your dreams are always so tough but romantic 😂

**Comment by oleanderghum** [comment]
i sit down, face to you,it's a long table with over 10 seats,

**Comment by oleanderghum** [comment]
Everybody is laughing about things people talk, so am I, and I shared some that makes me not look so embarrassed there, but I can't stay any second longer

**Comment by oleanderghum** [comment]
It's a red brick room, with candles, like a room of castle, cold, wet, noisy inside but quiet outside.

**Comment by oleanderghum** [comment]
Then it's dinner time, you said you need to leave, for another appointment, then you leave with a male co-worker of mine

**Comment by shayymaa** [comment]
sounds like a British drama scene

**Comment by shayymaa** [comment]
Who’s that

**Comment by oleanderghum** [comment]
I text you, after dinner all people would be dismissed, then we can leave together, forget about your appointment and come back

**Comment by oleanderghum** [comment]
Can't recall

**Comment by shayymaa** [comment]
pity

**Comment by oleanderghum** [comment]
Thank god you came back to the room and sit

**Comment by oleanderghum** [comment]
I walk out to another room,raining outside, text  you to come over, minutes later, you walk in

**Comment by shayymaa** [comment]
Did you kiss me?

**Comment by oleanderghum** [comment]
We kiss, kiss, kiss, and kiss.And the rain flood in the room, we climb to the roof, and we kiss, kiss, kiss

**Comment by shayymaa** [comment]
thats what I want

**Comment by oleanderghum** [comment]
Then you leave

**Comment by oleanderghum** [comment]
😇

**Comment by shayymaa** [comment]
how about you

**Comment by oleanderghum** [comment]
Keep lying on the ground 😇

**Comment by shayymaa** [comment]
where did I go

**Comment by oleanderghum** [comment]
I don't know, you just left

**Comment by shayymaa** [comment]
You just let me go?oh my...

**Comment by oleanderghum** [comment]
No, it was not me...it was like...you kiss me, comfort me, job done, then you left

**Comment by shayymaa** [comment]
Sounds I’m a libertine 🤔

**Comment by oleanderghum** [comment]
Cool girl like you😂😂

**Comment by shayymaa** [comment]
Is that a compliment? Fancy me?

**Comment by oleanderghum** [comment]
Yeah you can take it as compliment 😎

**Comment by oleanderghum** [comment]
[https://weibo.com/2150511032/G1ozClvKF?ref=feedsdk&type=comment#_rnd1517715767736](url)

**Comment by oleanderghum** [comment]
https://weibo.com/2150511032/G1ozClvKF?ref=feedsdk&type=repost#_rnd1517715767736

**Comment by oleanderghum** [comment]
Check this

**Comment by oleanderghum** [comment]
And awesome comments

**Comment by shayymaa** [comment]
ohhhh

**Comment by shayymaa** [comment]
Comment Top 1,what I did just like this,a piece of shit . hhhhhhh
