### ISSUE TITLE
Spring

### ISSUE THREAD

**Issue by oleanderghum** [oleanderghum/xx#4]

**Comment by oleanderghum** [comment]
Here comes spring again

**Comment by oleanderghum** [comment]
[Mazzy Star - Look On Down From The Bridge.mp3.zip](https://github.com/oleanderghum/xx/files/1692490/Mazzy.Star.-.Look.On.Down.From.The.Bridge.mp3.zip)

**Comment by shayymaa** [comment]
Can’t open it here

**Comment by shayymaa** [comment]
But I found it

**Comment by shayymaa** [comment]
Just answered a phone call,from a girl  ，WangYin，your student.asked mesome questions and said whether I’m your cute fan.i said yes hhhhhh

**Comment by oleanderghum** [comment]
I know fan but what is _cute fan_

**Comment by oleanderghum** [comment]
Does fan have a rank now?😆

**Comment by shayymaa** [comment]
fan for you，cute for me

**Comment by shayymaa** [comment]
only for me，we add cute，you can understand by this way

**Comment by oleanderghum** [comment]
Okay, cute you hahahahaha, I get it.Then some salesman call in, ask you if you are a cute customer.Cops call in, ask you are you a cute suspect. Wonderful!

**Comment by shayymaa** [comment]
emmmmm

**Comment by shayymaa** [comment]
are you playing a drama...on me？

**Comment by shayymaa** [comment]
we make a change then，are you a fan of me?

**Comment by shayymaa** [comment]
dont you know the word“小迷妹”，ｉcalled myself cute fan this way😌😌🙈🙈

**Comment by oleanderghum** [comment]
Thank you for the Chinese lesson,understood this time.

**Comment by shayymaa** [comment]
my cute old-fogey

**Comment by oleanderghum** [comment]
Oh wow thank you again for widen my vocabulary🙂

**Comment by shayymaa** [comment]
ambitious girl

**Comment by shayymaa** [comment]
be not satisfied with being a student?hiahiahiahia

**Comment by oleanderghum** [comment]
Teach me more

**Comment by shayymaa** [comment]
what do you want

**Comment by oleanderghum** [comment]
Anything you wanna teach

**Comment by shayymaa** [comment]
ohh that beats me

**Comment by shayymaa** [comment]
All tricks have been exhausted

**Comment by oleanderghum** [comment]
**# WHAT!!!!**

**Comment by oleanderghum** [comment]
#  **NO FUN!**

**Comment by shayymaa** [comment]
All talents faded away

**Comment by shayymaa** [comment]
When I saw you

**Comment by oleanderghum** [comment]
Waiting for some funny stuff 😑

**Comment by oleanderghum** [comment]
And then you fade away?????????

**Comment by shayymaa** [comment]
I fade away?? fade away where?🙂

**Comment by shayymaa** [comment]
Am I boring you??you bad guy

**Comment by shayymaa** [comment]
ohh pity，but you can only bear with me.hhhhhhhh

**Comment by shayymaa** [comment]
It’s too late

**Comment by oleanderghum** [comment]
No, I mean I thought there would be some some thing, sort of beyond my imagination

**Comment by shayymaa** [comment]
Keep on imagining,maybe there will be

**Comment by oleanderghum** [comment]
😏😏😏😏😏😈😈😈

**Comment by oleanderghum** [comment]
Late?

**Comment by shayymaa** [comment]
Late means you cannot run away

**Comment by oleanderghum** [comment]
Never want to

**Comment by shayymaa** [comment]
You can think about it but no way to get it

**Comment by shayymaa** [comment]
that will be a bit of fun

**Comment by oleanderghum** [comment]
Oh seems like you got everything under control huh

**Comment by shayymaa** [comment]
Oh no I'm not that big

**Comment by oleanderghum** [comment]
Hahahahaha

**Comment by shayymaa** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/36102568/35776319-0ff3c258-09d5-11e8-9a88-597efcdafd0c.jpg)

**Comment by shayymaa** [comment]
Strangely, when I miss you so much that day, I found that I really wanted an ice cream

**Comment by shayymaa** [comment]
so ｉate an ice cream yesterday night

**Comment by shayymaa** [comment]
finally found still missing you

**Comment by oleanderghum** [comment]
It's poetry

**Comment by shayymaa** [comment]
maybe just an excuse for an ice cream,hhhhh

**Comment by shayymaa** [comment]
and maybe I'll miss you every time ｉeat an ice cream i guess ,since yesterday

**Comment by shayymaa** [comment]
I just want to express my missing words actually and can’t find a proper way

**Comment by shayymaa** [comment]
oh my...whats wrong with me,😂😂😂kinda bashfully

**Comment by shayymaa** [comment]
cuz couldn't express it before,here comes a chance now

**Comment by oleanderghum** [comment]
Interesting, every time I miss you I grab a beer

**Comment by shayymaa** [comment]
oh mine is more lovely

**Comment by oleanderghum** [comment]
After all I'm an alcoholic

**Comment by shayymaa** [comment]
the difference is ,I will get colder,you are feeling warmer

**Comment by oleanderghum** [comment]
So we need to, like, mix?

**Comment by shayymaa** [comment]
we'll try

**Comment by oleanderghum** [comment]
You are giving me fantasy

**Comment by shayymaa** [comment]
what kind of

**Comment by oleanderghum** [comment]
A lot

**Comment by shayymaa** [comment]
cuz my...mix advice today?

**Comment by shayymaa** [comment]
😏

**Comment by oleanderghum** [comment]
Yes

**Comment by oleanderghum** [comment]
What picture?
